---
title: "Climate Risk Profiles - Training notebook"
output: html_notebook
author: A. Esquivel, C. Saavedra, H. Achicanoy, A. Ghosh, J. Ramirez-Villegas
date: September, 2021
---

```{=html}
<style type="text/css">
.main-container {
  max-width: 1800px;
  margin-left: auto;
  margin-right: auto;
}
</style>
```

------------------------------------------------------------------------

R options

```{r,echo=TRUE}
options(warn = -1, scipen = 999)

# Sourcing functions
source('https://raw.githubusercontent.com/haachicanoy/wfp_training/main/risk_profiles/code/_main_functions.R')
source('https://raw.githubusercontent.com/haachicanoy/wfp_training/main/risk_profiles/code/_get_soil_data.R')
source('https://raw.githubusercontent.com/haachicanoy/wfp_training/main/risk_profiles/code/_get_his_clim.R')
source('https://raw.githubusercontent.com/haachicanoy/wfp_training/main/risk_profiles/code/_get_dws_fut_clim.R')
source('https://raw.githubusercontent.com/haachicanoy/wfp_training/main/risk_profiles/code/_get_bc_fut_clim.R')
source('https://raw.githubusercontent.com/haachicanoy/wfp_training/main/risk_profiles/code/_calc_indices.R')
source('https://raw.githubusercontent.com/haachicanoy/wfp_training/main/risk_profiles/code/_calc_spi_drought.R')
```

Root path definition

```{r}
OSys <<- Sys.info()[1]
root <<- switch(OSys,
                'Linux'   = '/home/jovyan/work',
                'Windows' = '//catalogue/Workspace14/WFP_ClimateRiskPr/Harold/WFP_ClimateRiskPr')
```

Country parameters

```{r}
country <- 'Burundi'
iso     <- 'BDI'
seasons <- list(s1 = c(2:7), s2 = c(9:12,1:2))
```

# Get input data

## Get soil

```{r}
# Output file
fl <- paste0(root,"/1.Data/soil/",iso,"/soilcp_data.fst")
# Function to obtain soil data
get_soil(iso = iso, outfile = fl)
# Load the resulting file
soil <- tidyfst::parse_fst(fl) %>% base::as.data.frame()
library(DT)
# Explore the output
DT::datatable(soil)
# Visualize the output:
# scp: soil water holding capacity
# ssat: volumetric moisture content at saturation
soil %>% ggplot2::ggplot(aes(x, y, fill = scp)) + ggplot2::geom_tile() + ggplot2::coord_equal() + ggplot2::theme_bw() + ggplot2::scale_fill_continuous(type = 'viridis')
```

## Get historical climate

```{r}
# Output file
fl <- paste0(root,"/1.Data/observed_data/",iso,"/",iso,".fst")
# Function to extract daily historical climate data
get_his_clim(iso = iso, outfile = fl)
# Load the first 10 rows from the full table
hclim <- tidyfst::parse_fst(fl) %>% tidyfst::slice_fst(1:10) %>% base::as.data.frame()
#hclim <- tidyfst::parse_fst(fl) %>% base::as.data.frame()
# Explore the output
DT::datatable(hclim)
# hclim %>% dplyr::select(id, x, y, tmax) %>% dplyr::group_by(id, x, y) %>% dplyr::summarise(tmax = mean(tmax, na.rm = T)) %>% ggplot2::ggplot(aes(x, y, fill = tmax)) + ggplot2::geom_tile() + ggplot2::coord_equal() + ggplot2::theme_bw() + ggplot2::scale_fill_continuous(type = 'viridis')
```

## Get future climate

### Apply downscaling to future data

```{r}
# Output file
gcms <- c('ACCESS-ESM1-5', 'EC-Earth3-Veg','INM-CM5-0','MPI-ESM1-2-HR','MRI-ESM2-0')
periods <- c('2021-2040','2041-2060')
# Function to extract daily future downscaled climate data per GCM and period
for(gcm in gcms){
  for(period in periods){
    fl <- paste0(root,"/1.Data/future_data/",gcm,"/",iso,"/downscale/",period,"/",iso,".fst")
    cat(paste0('Performing downscaling for model: ',gcm,' and period: ',period))
    get_dws_fut_clim(iso = iso,
                     gcm = gcm,
                     period = period,
                     ncores = 10,
                     outfile = fl)
  }
}
# Load the resulting file
fl <- paste0(root,"/1.Data/future_data/ACCESS-ESM1-5/",iso,"/downscale/2021-2040/",iso,".fst")
fclim <- tidyfst::parse_fst(fl) %>% tidyfst::slice_fst(1:10) %>% base::as.data.frame()
# Explore the output
DT::datatable(fclim)
```

### Apply bias-correction to future climate

```{r}
# Output file
gcms <- c('ACCESS-ESM1-5', 'EC-Earth3-Veg','INM-CM5-0','MPI-ESM1-2-HR','MRI-ESM2-0')
periods <- c('2021-2040','2041-2060')
# Function to obtain daily future bias-corrected climate data per GCM and period
for(gcm in gcms){
  for(period in periods){
    fl <- paste0(root,"/1.Data/future_data/",gcm,"/",iso,"/bias_corrected/",period,"/",iso,".fst")
    cat(paste0('Performing bias-correction for model: ',gcm,' and period: ',period))
    get_bc_fut_clim(iso = iso,
                    gcm = gcm,
                    period = period,
                    ncores = 10,
                    outfile = fl)
  }
}
# Load the resulting file
fl <- paste0(root,"/1.Data/future_data/ACCESS-ESM1-5/",iso,"/bias_corrected/2021-2040/",iso,".fst")
fclim <- tidyfst::parse_fst(fl) %>% tidyfst::slice_fst(1:10) %>% base::as.data.frame()
# Explore the output
DT::datatable(fclim)
```

# Compute climate indices

## Historical

```{r}
infile <- paste0(root,"/1.Data/observed_data/",iso,"/",iso,".fst")
outfile <- paste0(root,"/7.Results/",country,"/past/",iso,"_indices.fst")
spi_out <- paste0(root,"/7.Results/",country,"/past/",iso,"_spi.fst")
calc_indices(iso     = iso,
             seasons = seasons,
             ncores  = 15,
             climate = infile,
             outfile = outfile,
             spi_out = spi_out)
# How much area per municipality is on average subject to ‘Major droughts’ (SPI < -1.5)
infile  <- paste0(root,"/7.Results/",country,"/past/",iso,"_spi.fst")
outfile <- paste0(root,'/7.Results/',country,'/past/',iso,'_spi_drought.fst')
calc_spi_drought(spi_data = infile,
                 output   = outfile,
                 country  = country,
                 iso      = iso,
                 seasons  = seasons)
# Load the resulting indices file
fl <- paste0(root,"/7.Results/",country,"/past/",iso,"_indices.fst")
indices <- tidyfst::parse_fst(fl) %>% base::as.data.frame()
```

```{r}
# Selected pixel
#      id      x         y
# 7650603 30.125 -3.125001
library(DT)
# Explore the output
DT::datatable(indices[1:10,])
# Visualize the output for one index-one year:
indices %>% dplyr::filter(year == 2019) %>% ggplot2::ggplot(aes(x, y, fill = ATR)) + ggplot2::geom_tile() + ggplot2::coord_equal() + ggplot2::theme_bw() + ggplot2::scale_fill_continuous(type = 'viridis') + ggplot2::facet_wrap(~season) + ggplot2::geom_point(data = indices %>% dplyr::filter(id == 7650603), aes(x, y), colour = 'red', size = 2.5)
# Visualize the output for time series
indices %>% dplyr::filter(id == 7650603) %>% ggplot2::ggplot(aes(x = year, y = ATR, colour = factor(season))) + ggplot2::geom_line() + ggplot2::theme_bw()
```

## Future

```{r}
models  <- c('ACCESS-ESM1-5', 'EC-Earth3-Veg','INM-CM5-0','MPI-ESM1-2-HR','MRI-ESM2-0')
periods <- c('2021-2040','2041-2060')
for(m in models){
  for(p in periods){
    infile  <- paste0(root,"/1.Data/future_data/",m,"/",iso,"/bias_corrected/",p,"/",iso,".fst")
    soilfl  <- paste0(root,"/1.Data/soil/",iso,"/soilcp_data.fst")
    outfile <- paste0(root,"/7.Results/",country,"/future/",m,"/",p,"/",iso,"_indices.fst")
    spi_out <- paste0(root,"/7.Results/",country,"/future/",m,"/",p,"/",iso,"_spi.fst")
    calc_indices(climate = infile,
                 soil    = soilfl,
                 seasons = seasons,
                 subset  = F,
                 ncores  = 15,
                 outfile = outfile,
                 spi_out = spi_out)
    infile  <- paste0(root,"/7.Results/",country,"/future/",m,"/",p,"/",iso,"_spi.fst")
    outfile <- paste0(root,"/7.Results/",country,"/future/",m,"/",p,"/",iso,"_spi_drought.fst")
    calc_spi_drought(spi_data = infile,
                     output   = outfile,
                     country  = country,
                     iso      = iso,
                     seasons  = seasons)
  }
}
```

End.
